#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Sep 27 12:05:13 2023

@author: zekibestia
"""

def sumaCadenas(n):
    
    if(len(n)==1):
        return int(n)
    else:
        #return print(n[0])
        suma=int(n[0])+sumaCadenas(n[1:])
        return suma

n="549"
suma=sumaCadenas(n)
print(suma)